package Model.Dota;

import java.util.ArrayList;

public class Heroes {

    public static final String shaker = "Earthshaker";
    public static final String sven = "Sven";
    public static final String tiny = "Tiny";
    public static final String kunkka = "Kunkka";
    public static final String beast = "Beastmaster";
    public static final String dk = "Dragon Knight";
    public static final String clock = "Clockwerk";
    public static final String omni = "Omniknight";
    public static final String huskar = "Huskar";
    public static final String alch = "Alchemist";
    public static final String brew = "Brewmaster";
    public static final String treant = "Treant Protector";
    public static final String io = "Io";
    public static final String cent = "Centaur Warrunner";
    public static final String timber = "Timbersaw";
    public static final String bb = "Bristleback";
    public static final String tusk = "Tusk";
    public static final String et = "Elder Titan";
    public static final String lc = "Legion Commander";
    public static final String es = "Earth Spirit";
    public static final String phoenix = "Phoenix";
    public static final String axe = "Axe";
    public static final String pudge = "Pudge";
    public static final String sk = "Sand King";
    public static final String slardar = "Slardar";
    public static final String tide = "Tidehunter";
    public static final String wk = "Wraith King";
    public static final String ls = "Lifestealer";
    public static final String ns = "Night Stalker";
    public static final String doom = "Doom";
    public static final String sb = "Spirit Breaker";
    public static final String lycan = "Lycan";
    public static final String ck = "Chaos Knight";
    public static final String undying = "Undying";
    public static final String magnus = "Magnus";
    public static final String aba = "Abaddon";
    public static final String pitlord = "Underlord";
    public static final String am = "Anti-Mage";
    public static final String drow = "Drow Ranger";
    public static final String jugg = "Juggernaut";
    public static final String mirana = "Mirana";
    public static final String morph = "Morphling";
    public static final String pl = "Phantom Lancer";
    public static final String venge = "Vengeful Spirit";
    public static final String riki = "Riki";
    public static final String sniper = "Sniper";
    public static final String ta = "Templar Assassin";
    public static final String luna = "Luna";
    public static final String bh = "Bounty Hunter";
    public static final String ursa = "Ursa";
    public static final String gyro = "Gyrocopter";
    public static final String ld = "Lone Druid";
    public static final String naga = "Naga Siren";
    public static final String troll = "Troll Warlord";
    public static final String ember = "Ember Spirit";
    public static final String mk = "Monkey King";
    public static final String pango = "Pangolier";
    public static final String bs = "Bloodseeker";
    public static final String sf = "Shadow Fiend";
    public static final String razor = "Razor";
    public static final String veno = "Venomancer";
    public static final String faceles = "Faceless Void";
    public static final String pa = "Phantom Assassin";
    public static final String viper = "Viper";
    public static final String clinkz = "Clinkz";
    public static final String brood = "Broodmother";
    public static final String weaver = "Weaver";
    public static final String spectre = "Spectre";
    public static final String meepo = "Meepo";
    public static final String nyx = "Nyx Assassin";
    public static final String slark = "Slark";
    public static final String medusa = "Medusa";
    public static final String tb = "Terrorblade";
    public static final String arc = "Arc Warden";
    public static final String cm = "Crystal Maiden";
    public static final String puck = "Puck";
    public static final String storm = "Storm Spirit";
    public static final String wr = "Windranger";
    public static final String zeus = "Zeus";
    public static final String lina = "Lina";
    public static final String ss = "Shadow Shaman";
    public static final String tinker = "Tinker";
    public static final String np = "Nature's Prophet";
    public static final String ench = "Enchantress";
    public static final String jakiro = "Jakiro";
    public static final String chen = "Chen";
    public static final String silencer = "Silencer";
    public static final String ogre = "Ogre Magi";
    public static final String rubick = "Rubick";
    public static final String disruptor = "Disruptor";
    public static final String kotl = "Keeper of the Light";
    public static final String sky = "Skywrath Mage";
    public static final String oracle = "Oracle";
    public static final String techies = "Techies";
    public static final String dw = "Dark Willow";
    public static final String bane = "Bane";
    public static final String lich = "Lich";
    public static final String lion = "Lion";
    public static final String wd = "Witch Doctor";
    public static final String enigma = "Enigma";
    public static final String necr = "Necrophos";
    public static final String warlock = "Warlock";
    public static final String qop = "Queen of Pain";
    public static final String dp = "Death Prophet";
    public static final String pugna = "Pugna";
    public static final String dazzle = "Dazzle";
    public static final String lesh = "Leshrac";
    public static final String ds = "Dark Seer";
    public static final String bat = "Batrider";
    public static final String aa = "Ancient Apparition";
    public static final String invoker = "Invoker";
    public static final String od = "Outworld Devourer";
    public static final String sd = "Shadow Demon";
    public static final String visage = "Visage";
    public static final String ww = "Winter Wyvern";
    public static final String grim = "Grimstroke";
    public static final String mars = "Mars";
    public static final String test = "Test";

    public static ArrayList<String> getAllHeroes(){
        ArrayList<String> heroeList = new ArrayList<>();
        heroeList.add(aba);
        heroeList.add(alch);
        heroeList.add(axe);
        heroeList.add(aa);
        heroeList.add(am);
        heroeList.add(arc);
        heroeList.add(axe);
        heroeList.add(bane);
        heroeList.add(bat);
        heroeList.add(beast);
        heroeList.add(bs);
        heroeList.add(bh);
        heroeList.add(brew);
        heroeList.add(bb);
        heroeList.add(brood);
        heroeList.add(cent);
        heroeList.add(ck);
        heroeList.add(chen);
        heroeList.add(clinkz);
        heroeList.add(clock);
        heroeList.add(cm);
        heroeList.add(ds);
        heroeList.add(dw);
        heroeList.add(dazzle);
        heroeList.add(dp);
        heroeList.add(disruptor);
        heroeList.add(doom);
        heroeList.add(dk);
        heroeList.add(drow);
        heroeList.add(es);
        heroeList.add(shaker);
        heroeList.add(et);
        heroeList.add(ember);
        heroeList.add(ench);
        heroeList.add(enigma);
        heroeList.add(faceles);
        heroeList.add(grim);
        heroeList.add(gyro);
        heroeList.add(huskar);
        heroeList.add(invoker);
        heroeList.add(io);
        heroeList.add(jakiro);
        heroeList.add(jugg);
        heroeList.add(kotl);
        heroeList.add(kunkka);
        heroeList.add(lc);
        heroeList.add(lesh);
        heroeList.add(lich);
        heroeList.add(ls);
        heroeList.add(lina);
        heroeList.add(lion);
        heroeList.add(ld);
        heroeList.add(luna);
        heroeList.add(lycan);
        heroeList.add(magnus);
        heroeList.add(mars);
        heroeList.add(medusa);
        heroeList.add(meepo);
        heroeList.add(mirana);
        heroeList.add(mk);
        heroeList.add(morph);
        heroeList.add(naga);
        heroeList.add(np);
        heroeList.add(necr);
        heroeList.add(ns);
        heroeList.add(nyx);
        heroeList.add(ogre);
        heroeList.add(omni);
        heroeList.add(oracle);
        heroeList.add(od);
        heroeList.add(pango);
        heroeList.add(pa);
        heroeList.add(pl);
        heroeList.add(phoenix);
        heroeList.add(puck);
        heroeList.add(pudge);
        heroeList.add(pugna);
        heroeList.add(qop);
        heroeList.add(razor);
        heroeList.add(riki);
        heroeList.add(rubick);
        heroeList.add(sk);
        heroeList.add(sd);
        heroeList.add(sf);
        heroeList.add(ss);
        heroeList.add(silencer);
        heroeList.add(sky);
        heroeList.add(slardar);
        heroeList.add(slark);
        heroeList.add(sniper);
        heroeList.add(spectre);
        heroeList.add(sb);
        heroeList.add(storm);
        heroeList.add(sven);
        heroeList.add(techies);
        heroeList.add(ta);
        heroeList.add(tb);
        heroeList.add(tide);
        heroeList.add(timber);
        heroeList.add(tinker);
        heroeList.add(tiny);
        heroeList.add(treant);
        heroeList.add(troll);
        heroeList.add(tusk);
        heroeList.add(pitlord);
        heroeList.add(undying);
        heroeList.add(ursa);
        heroeList.add(venge);
        heroeList.add(veno);
        heroeList.add(viper);
        heroeList.add(visage);
        heroeList.add(warlock);
        heroeList.add(weaver);
        heroeList.add(wr);
        heroeList.add(ww);
        heroeList.add(wd);
        heroeList.add(wk);
        heroeList.add(zeus);
        return heroeList;
    }


}
