package Model.TelegramBot;

public enum BotState {
    START, PICKING_FIRST_LETTER, PICKING_HERO, CONFIRMING, CONFIRMING_LIVE_GAME, CREATING_EXCEL,
    PICKING_HERO_TO_CHANGE, SUBSCRIPTION_MODE, ENTERING_SUBSCRIPTION_CODE, PICKING_LIVE_GAME,
    CHOOSING_ANALYSER_MODE;
}
